name: Build lib

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Prepare build sources
        run: |
          sed -i 's/\(tsc\) .*$/\1",/' package.json
          bun add -d @types/node @types/emscripten
          mkdir utils
          cd src && cp -r utils.ts jsyaml.ts pyyaml.ts converter.ts types ../utils
          cd -
          cat > tsconfig.json << 'EOF'
          {
            "compilerOptions": {
              "declaration": true,
              "declarationMap": true,
              "target": "ES2020",
              "rootDir": "./utils",
              "module": "commonjs",
              "types": ["node", "emscripten"],
              "outDir": "./dist",
              "sourceMap": false
            },
            "include": ["utils", "utils/types"]
          }
          EOF

      - name: Build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
